{{- $name := include "svai.name" . -}}
{{- $dns := include "svai.dns" . -}}
{{- $svcPort := .Values.service.port -}}


apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name  }}-tls
spec:
  dnsNames:
  - {{ $dns }}
  issuerRef:
    name: letsencrypt-svai
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: {{ $name }}-tls-certificate
  privateKey:
    algorithm: ECDSA