{{- range .Values.environment.secrets }}
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: {{ .nameInKeyVault }}
spec:
  vault:
    name: {{ .vault }}
    object:
      type: secret
      name: {{ .nameInKeyVault }}
---
{{- end }}