apiVersion: v1
kind: Service
metadata:
  name: {{ include "svai.name" . }}
  labels:
    {{- include "svai.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "svai.selectorLabels" . | nindent 4 }}
