{{- if .Values.watchAllNamespaces }}
{{- $_ := set .Values "roleType" "ClusterRole" -}}
{{- $_ := set .Values "roleBindingType" "ClusterRoleBinding" -}}
{{- else -}}
{{- $_ := set .Values "roleType" "Role" -}}
{{- $_ := set .Values "roleBindingType" "RoleBinding" -}}
{{- end -}}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/ClusterRole" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: {{ .Values.roleType }}
metadata:
  name: {{ template "azure-key-vault-controller.fullname" . }}
  labels:
    app: {{ template "azure-key-vault-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - delete
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
---
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/ClusterRole" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: {{ .Values.roleType }}
metadata:
  name: {{ template "azure-key-vault-controller.fullname" . }}-reader
  labels:
    app: {{ template "azure-key-vault-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
  - watch
---
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/ClusterRoleBinding" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: {{ .Values.roleBindingType }}
metadata:
  name: {{ template "azure-key-vault-controller.fullname" . }}
  labels:
    app: {{ template "azure-key-vault-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ template "azure-key-vault-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: {{ .Values.roleType }}
  name: {{ template "azure-key-vault-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/ClusterRoleBinding" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: {{ .Values.roleBindingType }}
metadata:
  name: {{ template "azure-key-vault-controller.fullname" . }}-reader
  labels:
    app: {{ template "azure-key-vault-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: {{ .Values.roleType }}
  name: {{ template "azure-key-vault-controller.fullname" . }}-reader
  apiGroup: rbac.authorization.k8s.io
