{{- if .Values.global.userDefinedMSI.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "akv2k8s.name" . }}-azureconfig
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
data:
  azure.json: |
    {
        "cloud": "{{ .Values.global.userDefinedMSI.azureCloudType }}",
        "tenantId": "{{ .Values.global.userDefinedMSI.tenantId }}",
        "subscriptionId": "{{ .Values.global.userDefinedMSI.subscriptionId }}",
        "aadClientId": "msi",
        "aadClientSecret": "msi",
        {{- if .Values.global.userDefinedMSI.useWorkloadIdentityExtension }}
        "useWorkloadIdentityExtension": true,
        {{- else }}
        "useManagedIdentityExtension": true,
        {{- end }}
        "userAssignedIdentityID": "{{ .Values.global.userDefinedMSI.msi }}",
    }
{{- end }}
