{{- if and .Values.controller.enabled .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "controller.serviceAccountName" . }}
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
    {{- with .Values.controller.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.controller.serviceAccount.annotations }}
  annotations:
  {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
