{{- if .Values.controller.enabled }}
{{- $metricsEnabled := default .Values.global.metrics.enabled .Values.controller.metrics.enabled }}
{{- $serviceMonEnabled := default .Values.global.metrics.serviceMonitor.enabled .Values.controller.metrics.serviceMonitor.enabled }}
{{- $interval := default .Values.global.metrics.serviceMonitor.interval .Values.controller.metrics.serviceMonitor.interval}}
{{- $labels := default .Values.global.metrics.serviceMonitor.additionalLabels .Values.controller.metrics.serviceMonitor.additionalLabels}}

{{- if and $metricsEnabled $serviceMonEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "akv2k8s.controller.fullname" . }}
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
    {{- include "akv2k8s.components.controller" . | nindent 4 }}
    {{- if $labels }}
    {{- toYaml $labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
      interval: {{ $interval }}
  selector:
    matchLabels:
      {{- include "akv2k8s.selectors" . | nindent 6 }}
      {{- include "akv2k8s.components.controller" . | nindent 6 }}
{{- end }}
{{- end }}
