{{- if .Values.global.env -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "akv2k8s.fullname" . }}-env
  labels:
    {{- include "akv2k8s.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.global.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end}}