# Create a akv2k8s reader cluster role
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/ClusterRole" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRole
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets # in order to inspect docker image with ImagePullSecrets
  verbs:
  - get
---

# Create a akv2k8s reader cluster role
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/ClusterRole" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRole
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-reader
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
  - watch
---

{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/ClusterRole" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRole
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-ca-bundle
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - update
  - delete
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
---

{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/Role" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: Role
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-ca-bundle
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
---

{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/ClusterRoleBinding" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-ca-bundle
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "azure-key-vault-to-kubernetes.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-ca-bundle
  apiGroup: rbac.authorization.k8s.io
---

{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/RoleBinding" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: RoleBinding
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-ca-bundle
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "azure-key-vault-to-kubernetes.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-ca-bundle
  apiGroup: rbac.authorization.k8s.io
---

{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/ClusterRoleBinding" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-sa
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ template "azure-key-vault-to-kubernetes.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}
---

# Give all service accounts read access to akvs
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1/ClusterRoleBinding" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-reader
  labels:
    app: {{ template "azure-key-vault-to-kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ template "azure-key-vault-to-kubernetes.fullname" . }}-reader
  apiGroup: rbac.authorization.k8s.io
