name: build and publish

on:
  push:
    branches:
    - master
    - '*-beta'
    paths:
    - '.github/workflows/build-akv2k8s.yaml'
    - 'stable/akv2k8s/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout master
      uses: actions/checkout@v3
      with:
        path: master

    - name: checkout gh-pages
      uses: actions/checkout@v3
      with:
        repository: sparebankenvest/helm-charts
        ref: gh-pages
        path: publish

    - name: Install Helm
      uses: ./master/.github/actions/install-helm

    - name: Build Helm Charts
      uses: ./master/.github/actions/build
      with:
        chart-name: akv2k8s

    - name: Release Helm Charts
      uses: ./master/.github/actions/release
      with:
        publish-token: ${{ secrets.GH_PAGES_TOKEN }}
